---
title: "FINM33165 Homework 1"
author: "Sarah Adilijiang"
output:
  pdf_document: default
  html_notebook: default
---

## Polynomial Regression

### (a)

$$p(D|M_n) = \int p(D,w|M_n)dw = \int \frac{p(D,w,M_n)}{p(M_n)}dw = \int \frac{p(D|w,M_n)\ p(w,M_n)}{p(M_n)}dw$$

$$= \int p(D|w,M_n) \ \frac{p(w,M_n)} {p(M_n)}\ dw = \int p(D|w,M_n) \ p(w|M_n)\ dw$$




### (b)

The design matrix:
$$
X_n = \left[\begin{matrix}
1 & x_0 & x_0^2 &  \cdots &  x_0^n \\
1 &  x_1 &  x_1^2 & \cdots & x_1^n \\
\vdots &  \vdots &  \vdots &  \vdots &  \vdots \\
1 &  x_{N-1} &  x_{N-1}^2 & \cdots & x_{N-1}^n \\
\end{matrix}\right]
$$

So:
$$y = X_nw + \sigma^2N(0,I_N)$$
where
$$y=(y_0,y_1,\cdots,y_{N-1})^T, \ \ \ w=(w_0,w_1,\cdots,w_n)^T  $$

Since $\Sigma_p$ is an $n\times n$ positive definite covariance matrix, so matrix $\Sigma_p$ is symmetric and all its eigenvalues are positive. And the inverse matrix $\Sigma_p^{-1}$ is also symmetric. And $\Sigma_p^{-1}\Sigma_p = \Sigma_p\Sigma_p^{-1} = I$.

Then the matrix $A = \left( \frac{1}{\sigma^2}X_n^TX_n + \Sigma_p^{-1} \right)^{-1}$ is also a symmetric matirx, i.e. $A = A^{-1}$. And note that $A^{-1}A = AA^{-1} = I$.

Thus the right side of the equation is:
$$(w-\mu)^TA^{-1}(w-\mu) + \frac{1}{\sigma^2} \left(y^Ty - \frac{1}{\sigma^2}y^TX_nA^TX_n^Ty \right)$$

$$= \left( w-A(\frac{1}{\sigma^2}X_n^Ty) \right)^T A^{-1} \left( w-A(\frac{1}{\sigma^2}X_n^Ty) \right) + \frac{1}{\sigma^2} \left(y^Ty - \frac{1}{\sigma^2}y^TX_nA^TX_n^Ty \right)$$

$$= \left( w^T - \frac{1}{\sigma^2}y^TX_nA \right) A^{-1} \left( w - \frac{1}{\sigma^2}AX_n^Ty \right) + \frac{1}{\sigma^2} \left(y^Ty - \frac{1}{\sigma^2}y^TX_nA^TX_n^Ty \right)$$

$$= w^TA^{-1}w - \frac{1}{\sigma^2}y^TX_nw - \frac{1}{\sigma^2}w^TX_n^Ty + \frac{1}{\sigma^4}y^TX_nAX_n^Ty + \frac{1}{\sigma^2}y^Ty - \frac{1}{\sigma^4}y^TX_nA^TX_n^Ty$$

$$= w^TA^{-1}w - \frac{1}{\sigma^2}y^TX_nw - \frac{1}{\sigma^2}w^TX_n^Ty + \frac{1}{\sigma^2}y^Ty$$

$$= w^T \left( \frac{1}{\sigma^2}X_n^TX_n + \Sigma_p^{-1} \right)w - \frac{1}{\sigma^2}y^TX_nw - \frac{1}{\sigma^2}w^TX_n^Ty + \frac{1}{\sigma^2}y^Ty$$

$$= \frac{1}{\sigma^2}w^TX_n^TX_nw + w^T\Sigma_p^{-1}w - \frac{1}{\sigma^2}y^TX_nw - \frac{1}{\sigma^2}w^TX_n^Ty + \frac{1}{\sigma^2}y^Ty$$

$$= \frac{1}{\sigma^2}  \left( w^TX_n^TX_nw - y^TX_nw - w^TX_n^Ty + y^Ty \right)  + w^T\Sigma_p^{-1}w$$

$$= \frac{1}{\sigma^2}(y^Ty - 2w^TX_n^Ty + w^TX_n^TX_nw) + w^T\Sigma_p^{-1}w$$
Note that $w^TX_n^Ty$ is a scalar, so $w^TX_n^Ty = (w^TX_n^Ty)^T = y^TX_nw$.



Since the left side of the equation is:
$$\frac{1}{\sigma^2}(y-X_nw)^T(y-X_nw) + w^T\Sigma_p^{-1}w$$

$$= \frac{1}{\sigma^2}(y^T-w^TX_n^T)(y-X_nw) + w^T\Sigma_p^{-1}w$$

$$= \frac{1}{\sigma^2}(y^Ty - 2w^TX_n^Ty + w^TX_n^TX_nw) + w^T\Sigma_p^{-1}w$$


Therefore, we have proved that:
$$
\frac{1}{\sigma^2}(y-X_nw)^T(y-X_nw) + w^T\Sigma_p^{-1}w \ = \ 
(w-\mu)^TA^{-1}(w-\mu) + \frac{1}{\sigma^2} \left(y^Ty - \frac{1}{\sigma^2}y^TX_nA^TX_n^Ty \right)
$$




### (c)
The left side of equation is:
$$N(y;X_nw,\sigma^2I_N) \ N(w;0,\Sigma_p)$$

$$= \frac{1}{2\pi^{N/2}} \frac{1}{(\text{det}\sigma^2I_N)^{1/2}} \exp \left\{-\frac{1}{2\sigma^2} (y-X_nw)^T(y-X_nw) \right\} \frac{1}{2\pi^{(n+1)/2}} \frac{1}{(\text{det}\Sigma_p)^{1/2}} \exp \left\{ -\frac{1}{2} w^T\Sigma_p^{-1}w \right\}$$

$$= \frac{1}{2\pi^{N/2}} \frac{1}{(\text{det}\sigma^2I_N)^{1/2}}  \frac{1}{2\pi^{(n+1)/2}} \frac{1}{(\text{det}\Sigma_p)^{1/2}}   \exp \left\{-\frac{1}{2} \left[ \frac{1}{\sigma^2} (y-X_nw)^T(y-X_nw) + w^T\Sigma_p^{-1}w \right] \right\}$$


From (b), we get that:
$$
\frac{1}{\sigma^2}(y-X_nw)^T(y-X_nw) + w^T\Sigma_p^{-1}w \ = \ 
(w-\mu)^TA^{-1}(w-\mu) + \frac{1}{\sigma^2} \left(y^Ty - \frac{1}{\sigma^2}y^TX_nA^TX_n^Ty \right)
$$
where
$$\mu = A(\frac{1}{\sigma^2}X_n^Ty) \ \ \text{and} \ \ A = \left( \frac{1}{\sigma^2}X_n^TX_n + \Sigma_p^{-1} \right)^{-1}$$



So the right side of equation is:
$$\frac{1}{2\pi^{N/2}} \frac{1}{(\text{det}\sigma^2I_N)^{1/2}}  \frac{1}{2\pi^{(n+1)/2}} \frac{1}{(\text{det}\Sigma_p)^{1/2}} \ (2\pi)^{(n+1)/2}(\text{det}A)^{1/2}$$

$$\times \exp\left\{ -\frac{1}{2} y^T \left( \frac{1}{\sigma^2}I_N - \frac{1}{\sigma^4}X_nA^TX_n^T \right)y \right\} \ N(w;A(\frac{1}{\sigma^2}X_n^Ty), A)$$

$$=  \ \ \ \ \ \ \ \ \frac{1}{2\pi^{N/2}} \frac{1}{(\text{det}\sigma^2I_N)^{1/2}}  \frac{1}{2\pi^{(n+1)/2}} \frac{1}{(\text{det}\Sigma_p)^{1/2}}$$

$$\times \exp\left\{ -\frac{1}{2} y^T \left( \frac{1}{\sigma^2}I_N - \frac{1}{\sigma^4}X_nA^TX_n^T \right)y \right\} \ \exp\left\{ -\frac{1}{2} \left[ (w-\mu)^TA^{-1}(w-\mu) \right] \right\}$$

Since:
$$\exp\left\{ -\frac{1}{2} y^T \left( \frac{1}{\sigma^2}I_N - \frac{1}{\sigma^4}X_nA^TX_n^T \right)y \right\} \ \exp\left\{ -\frac{1}{2} \left[ (w-\mu)^TA^{-1}(w-\mu) \right] \right\}$$

$$=  \exp\left\{ -\frac{1}{2} y^T \left( \frac{1}{\sigma^2}I_N - \frac{1}{\sigma^4}X_nA^TX_n^T \right)y -\frac{1}{2} \left[ \frac{1}{\sigma^2}(y-X_nw)^T(y-X_nw) + w^T\Sigma_p^{-1}w - \frac{1}{\sigma^2} \left(y^Ty - \frac{1}{\sigma^2}y^TX_nA^TX_n^Ty \right) \right] \right\}$$

$$= \exp \left\{-\frac{1}{2} \left[ \frac{1}{\sigma^2} (y-X_nw)^T(y-X_nw) + w^T\Sigma_p^{-1}w \right] \right\}$$

$$\times \exp\left\{ -\frac{1}{2} \left[  y^T \left( \frac{1}{\sigma^2}I_N - \frac{1}{\sigma^4}X_nA^TX_n^T \right)y - \frac{1}{\sigma^2} \left(y^Ty - \frac{1}{\sigma^2}y^TX_nA^TX_n^Ty \right) \right] \right\}$$

$$= \exp \left\{-\frac{1}{2} \left[ \frac{1}{\sigma^2} (y-X_nw)^T(y-X_nw) + w^T\Sigma_p^{-1}w \right] \right\}$$


Thus, the right side equals to:
$$\frac{1}{2\pi^{N/2}} \frac{1}{(\text{det}\sigma^2I_N)^{1/2}}  \frac{1}{2\pi^{(n+1)/2}} \frac{1}{(\text{det}\Sigma_p)^{1/2}} \exp \left\{-\frac{1}{2} \left[ \frac{1}{\sigma^2} (y-X_nw)^T(y-X_nw) + w^T\Sigma_p^{-1}w \right] \right\}$$
which is the same as the left side.


Therefore, the equation has been proved.





### (d)
$$\int N(y;X_nw,\sigma^2I_N) \ N(w;0,\Sigma_p)$$

$$= \frac{1}{2\pi^{N/2}} \frac{1}{(\text{det}\sigma^2I_N)^{1/2}}  \frac{1}{2\pi^{(n+1)/2}} \frac{1}{(\text{det}\Sigma_p)^{1/2}} \ (2\pi)^{(n+1)/2}(\text{det}A)^{1/2}$$

$$\ \ \ \ \ \ \ \ \exp\left\{ -\frac{1}{2} y^T \left( \frac{1}{\sigma^2}I_N - \frac{1}{\sigma^4}X_nA^TX_n^T \right)y \right\} \ \int N(w;A(\frac{1}{\sigma^2}X_n^Ty), A)$$

$$= \frac{1}{2\pi^{N/2}} \frac{1}{(\text{det}\sigma^2I_N)^{1/2}}  \frac{1}{2\pi^{(n+1)/2}} \frac{1}{(\text{det}\Sigma_p)^{1/2}} \ (2\pi)^{(n+1)/2}(\text{det}A)^{1/2} \ \exp\left\{ -\frac{1}{2} y^T \left( \frac{1}{\sigma^2}I_N - \frac{1}{\sigma^4}X_nA^TX_n^T \right)y \right\}$$

$$= \frac{(\text{det}A)^{1/2}}{(2\pi)^{N/2} (\sigma^{2N})^{1/2} (\text{det}\Sigma_p)^{1/2}} \ \exp\left\{ -\frac{1}{2} y^T \left( \frac{1}{\sigma^2}I_N - \frac{1}{\sigma^4}X_nA^TX_n^T \right)y \right\}$$

$$= \frac{ \sqrt{\text{det}A}} {(2\pi)^{N/2} \sigma^{N} \sqrt{\text{det}\Sigma_p}} \ \exp\left\{ -\frac{1}{2} y^T \left( \frac{1}{\sigma^2}I_N - \frac{1}{\sigma^4}X_nA^TX_n^T \right)y \right\}$$




### (e)

This is down in the jupyter notebook file.



















